/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.FornecedorController;
import crud.FornecedorCRUD;
import domain.Fornecedor;

/**
 *
 * @author Adriano
 */
public class FrmCadastrarFornecedor extends javax.swing.JDialog {

    /**
     * Creates new form FrmCadastrarFornecedor
     */
    public FrmCadastrarFornecedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        pnlDadosFornecedor = new javax.swing.JPanel();
        tfFornecedorNome = new javax.swing.JTextField();
        lblNomeFornecedor = new javax.swing.JLabel();
        tfFornecedorCnpj = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        tfFornecedorCodigo = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        lblNomeFornecedor1 = new javax.swing.JLabel();
        tfFornecedorEndereco = new javax.swing.JTextField();
        lblNomeFornecedor2 = new javax.swing.JLabel();
        tfFornecedorBairro = new javax.swing.JTextField();
        lblNomeFornecedor3 = new javax.swing.JLabel();
        tfFornecedorUf = new javax.swing.JTextField();
        lblNomeFornecedor4 = new javax.swing.JLabel();
        tfFornecedorTelResidencia = new javax.swing.JTextField();
        lblNomeFornecedor5 = new javax.swing.JLabel();
        tfFornecedorTelCelular = new javax.swing.JTextField();
        lblNomeFornecedor6 = new javax.swing.JLabel();
        lblNomeFornecedor7 = new javax.swing.JLabel();
        tfFornecedorEmail = new javax.swing.JTextField();
        lblNomeFornecedor8 = new javax.swing.JLabel();
        tfFornecedorSite = new javax.swing.JTextField();
        lblNomeFornecedor9 = new javax.swing.JLabel();
        tfFornecedorVendedor = new javax.swing.JTextField();
        btnCadastrarFornecedor = new javax.swing.JButton();
        btnAlterarFornecedor = new javax.swing.JButton();
        lblNomeFornecedor10 = new javax.swing.JLabel();
        tfFornecedorCelularVendedor = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(153, 153, 255));
        jPanel4.setBorder(null);

        jLabel51.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel51.setText("Dados do Fornecedor");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel51, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel51)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlDadosFornecedor.setBackground(new java.awt.Color(204, 204, 255));
        pnlDadosFornecedor.setBorder(null);

        tfFornecedorNome.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        lblNomeFornecedor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNomeFornecedor.setForeground(new java.awt.Color(0, 69, 139));
        lblNomeFornecedor.setText("Nome / Razão Social:");

        tfFornecedorCnpj.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(0, 69, 139));
        jLabel50.setText("CNPJ:");

        tfFornecedorCodigo.setBackground(new java.awt.Color(204, 255, 204));
        tfFornecedorCodigo.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        tfFornecedorCodigo.setForeground(new java.awt.Color(255, 0, 0));
        tfFornecedorCodigo.setBorder(null);

        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(0, 69, 139));
        jLabel49.setText("Código:");

        lblNomeFornecedor1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNomeFornecedor1.setForeground(new java.awt.Color(0, 69, 139));
        lblNomeFornecedor1.setText("Endereço:");

        tfFornecedorEndereco.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        lblNomeFornecedor2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNomeFornecedor2.setForeground(new java.awt.Color(0, 69, 139));
        lblNomeFornecedor2.setText("Bairro:");

        tfFornecedorBairro.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        lblNomeFornecedor3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNomeFornecedor3.setForeground(new java.awt.Color(0, 69, 139));
        lblNomeFornecedor3.setText("UF:");

        tfFornecedorUf.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        lblNomeFornecedor4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNomeFornecedor4.setForeground(new java.awt.Color(0, 69, 139));
        lblNomeFornecedor4.setText("Telefones:");

        tfFornecedorTelResidencia.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        lblNomeFornecedor5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNomeFornecedor5.setForeground(new java.awt.Color(0, 69, 139));
        lblNomeFornecedor5.setText("Res:");

        tfFornecedorTelCelular.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        lblNomeFornecedor6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNomeFornecedor6.setForeground(new java.awt.Color(0, 69, 139));
        lblNomeFornecedor6.setText("Celular:");

        lblNomeFornecedor7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNomeFornecedor7.setForeground(new java.awt.Color(0, 69, 139));
        lblNomeFornecedor7.setText("E-mail:");

        tfFornecedorEmail.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        lblNomeFornecedor8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNomeFornecedor8.setForeground(new java.awt.Color(0, 69, 139));
        lblNomeFornecedor8.setText("Site:");

        tfFornecedorSite.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        lblNomeFornecedor9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNomeFornecedor9.setForeground(new java.awt.Color(0, 69, 139));
        lblNomeFornecedor9.setText("Vendedor:");

        tfFornecedorVendedor.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        btnCadastrarFornecedor.setBackground(new java.awt.Color(102, 0, 102));
        btnCadastrarFornecedor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCadastrarFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cadastroPqn.png"))); // NOI18N
        btnCadastrarFornecedor.setToolTipText("Cadastrar");
        btnCadastrarFornecedor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCadastrarFornecedor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCadastrarFornecedor.setPreferredSize(new java.awt.Dimension(0, 0));

        btnAlterarFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/AlterarPq.png"))); // NOI18N
        btnAlterarFornecedor.setToolTipText("Alterar");
        btnAlterarFornecedor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAlterarFornecedor.setEnabled(false);

        lblNomeFornecedor10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNomeFornecedor10.setForeground(new java.awt.Color(0, 69, 139));
        lblNomeFornecedor10.setText("Celular:");

        tfFornecedorCelularVendedor.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        javax.swing.GroupLayout pnlDadosFornecedorLayout = new javax.swing.GroupLayout(pnlDadosFornecedor);
        pnlDadosFornecedor.setLayout(pnlDadosFornecedorLayout);
        pnlDadosFornecedorLayout.setHorizontalGroup(
            pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosFornecedorLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDadosFornecedorLayout.createSequentialGroup()
                        .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNomeFornecedor)
                            .addComponent(lblNomeFornecedor1)
                            .addComponent(lblNomeFornecedor2)
                            .addComponent(lblNomeFornecedor4)
                            .addComponent(lblNomeFornecedor7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDadosFornecedorLayout.createSequentialGroup()
                                .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tfFornecedorBairro)
                                    .addGroup(pnlDadosFornecedorLayout.createSequentialGroup()
                                        .addComponent(lblNomeFornecedor5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                                        .addComponent(tfFornecedorTelResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(tfFornecedorEmail)
                                    .addComponent(tfFornecedorVendedor))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(pnlDadosFornecedorLayout.createSequentialGroup()
                                        .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblNomeFornecedor6)
                                            .addComponent(lblNomeFornecedor3)
                                            .addGroup(pnlDadosFornecedorLayout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(lblNomeFornecedor8)
                                                .addGap(21, 21, 21)))
                                        .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(tfFornecedorTelCelular, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfFornecedorUf, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tfFornecedorSite, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDadosFornecedorLayout.createSequentialGroup()
                                        .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(pnlDadosFornecedorLayout.createSequentialGroup()
                                                .addComponent(btnAlterarFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnCadastrarFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(pnlDadosFornecedorLayout.createSequentialGroup()
                                                .addComponent(lblNomeFornecedor10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tfFornecedorCelularVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addContainerGap(21, Short.MAX_VALUE))))
                            .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(tfFornecedorNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                                .addComponent(tfFornecedorEndereco, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addComponent(lblNomeFornecedor9)
                    .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(pnlDadosFornecedorLayout.createSequentialGroup()
                            .addComponent(jLabel50)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfFornecedorCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDadosFornecedorLayout.createSequentialGroup()
                            .addComponent(jLabel49)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tfFornecedorCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        pnlDadosFornecedorLayout.setVerticalGroup(
            pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosFornecedorLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel49)
                    .addComponent(tfFornecedorCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel50)
                    .addComponent(tfFornecedorCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfFornecedorNome, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomeFornecedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeFornecedor1)
                    .addComponent(tfFornecedorEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeFornecedor2)
                    .addComponent(tfFornecedorBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfFornecedorUf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomeFornecedor3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeFornecedor4)
                    .addComponent(tfFornecedorTelResidencia, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomeFornecedor5)
                    .addComponent(tfFornecedorTelCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomeFornecedor6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfFornecedorEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomeFornecedor7)
                    .addComponent(lblNomeFornecedor8)
                    .addComponent(tfFornecedorSite, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeFornecedor9)
                    .addComponent(tfFornecedorVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomeFornecedor10)
                    .addComponent(tfFornecedorCelularVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCadastrarFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAlterarFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlDadosFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDadosFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarFornecedor;
    private javax.swing.JButton btnCadastrarFornecedor;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblNomeFornecedor;
    private javax.swing.JLabel lblNomeFornecedor1;
    private javax.swing.JLabel lblNomeFornecedor10;
    private javax.swing.JLabel lblNomeFornecedor2;
    private javax.swing.JLabel lblNomeFornecedor3;
    private javax.swing.JLabel lblNomeFornecedor4;
    private javax.swing.JLabel lblNomeFornecedor5;
    private javax.swing.JLabel lblNomeFornecedor6;
    private javax.swing.JLabel lblNomeFornecedor7;
    private javax.swing.JLabel lblNomeFornecedor8;
    private javax.swing.JLabel lblNomeFornecedor9;
    private javax.swing.JPanel pnlDadosFornecedor;
    private javax.swing.JTextField tfFornecedorBairro;
    private javax.swing.JTextField tfFornecedorCelularVendedor;
    private javax.swing.JTextField tfFornecedorCnpj;
    private javax.swing.JTextField tfFornecedorCodigo;
    private javax.swing.JTextField tfFornecedorEmail;
    private javax.swing.JTextField tfFornecedorEndereco;
    private javax.swing.JTextField tfFornecedorNome;
    private javax.swing.JTextField tfFornecedorSite;
    private javax.swing.JTextField tfFornecedorTelCelular;
    private javax.swing.JTextField tfFornecedorTelResidencia;
    private javax.swing.JTextField tfFornecedorUf;
    private javax.swing.JTextField tfFornecedorVendedor;
    // End of variables declaration//GEN-END:variables
}
