/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.FornecedorController;
import crud.FornecedorCRUD;
import domain.Fornecedor;
import java.awt.Color;

/**
 *
 * @author Adriano
 */
public class FrmCadastrarFornecedor extends javax.swing.JDialog {

    /**
     * Creates new form FrmCadastrarFornecedor
     */
    public FrmCadastrarFornecedor(java.awt.Frame parent, boolean modal,boolean op) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.pnlFornecedorOpBusca.setVisible(op);
        this.pnlFornecedorTituloOpBusca.setVisible(op);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        pnlDadosFornecedor = new javax.swing.JPanel();
        tfFornecedorNome = new javax.swing.JTextField();
        lblNomeFornecedor = new javax.swing.JLabel();
        tfFornecedorCnpj = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        tfFornecedorCodigo = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        lblNomeFornecedor1 = new javax.swing.JLabel();
        tfFornecedorEndereco = new javax.swing.JTextField();
        lblNomeFornecedor2 = new javax.swing.JLabel();
        tfFornecedorBairro = new javax.swing.JTextField();
        lblNomeFornecedor3 = new javax.swing.JLabel();
        tfFornecedorUf = new javax.swing.JTextField();
        lblNomeFornecedor4 = new javax.swing.JLabel();
        tfFornecedorTelFixo = new javax.swing.JTextField();
        tfFornecedorTelCelular = new javax.swing.JTextField();
        lblNomeFornecedor6 = new javax.swing.JLabel();
        lblNomeFornecedor7 = new javax.swing.JLabel();
        tfFornecedorEmail = new javax.swing.JTextField();
        lblNomeFornecedor8 = new javax.swing.JLabel();
        tfFornecedorSite = new javax.swing.JTextField();
        lblNomeFornecedor9 = new javax.swing.JLabel();
        tfFornecedorVendedor = new javax.swing.JTextField();
        btnCadastrarFornecedor = new javax.swing.JButton();
        btnAlterarFornecedor = new javax.swing.JButton();
        lblNomeFornecedor10 = new javax.swing.JLabel();
        tfFornecedorRamalVendedor = new javax.swing.JTextField();
        lblNomeFornecedor11 = new javax.swing.JLabel();
        tfFornecedorEndereco1 = new javax.swing.JTextField();
        lblNomeFornecedor12 = new javax.swing.JLabel();
        lblNomeFornecedor13 = new javax.swing.JLabel();
        tfFornecedorUf1 = new javax.swing.JTextField();
        tfFornecedorEndereco2 = new javax.swing.JTextField();
        lblNomeFornecedor14 = new javax.swing.JLabel();
        tfFornecedorEndereco3 = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        pnlFornecedorOpBusca = new javax.swing.JPanel();
        tfFornecedorOpBuscaCod = new javax.swing.JTextField();
        tfFornecedorOpBuscaCnpj = new javax.swing.JTextField();
        tfFornecedorOpBuscaNome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlFornecedorResultBusca = new javax.swing.JList();
        pnlFornecedorTituloOpBusca = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel4.setBackground(new java.awt.Color(153, 153, 255));
        jPanel4.setBorder(null);

        jLabel51.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel51.setText("Dados do Fornecedor");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel51, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel51)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlDadosFornecedor.setBackground(new java.awt.Color(204, 204, 255));
        pnlDadosFornecedor.setBorder(null);

        tfFornecedorNome.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        tfFornecedorNome.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblNomeFornecedor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNomeFornecedor.setForeground(new java.awt.Color(0, 69, 139));
        lblNomeFornecedor.setText("Nome / Razão Social:");

        tfFornecedorCnpj.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        tfFornecedorCnpj.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(0, 69, 139));
        jLabel50.setText("CNPJ:");

        tfFornecedorCodigo.setBackground(new java.awt.Color(204, 255, 204));
        tfFornecedorCodigo.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        tfFornecedorCodigo.setForeground(new java.awt.Color(255, 0, 0));
        tfFornecedorCodigo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfFornecedorCodigo.setBorder(null);

        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(0, 69, 139));
        jLabel49.setText("Código:");

        lblNomeFornecedor1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNomeFornecedor1.setForeground(new java.awt.Color(0, 69, 139));
        lblNomeFornecedor1.setText("Logradouro:");

        tfFornecedorEndereco.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        tfFornecedorEndereco.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblNomeFornecedor2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNomeFornecedor2.setForeground(new java.awt.Color(0, 69, 139));
        lblNomeFornecedor2.setText("Bairro:");

        tfFornecedorBairro.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        tfFornecedorBairro.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblNomeFornecedor3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNomeFornecedor3.setForeground(new java.awt.Color(0, 69, 139));
        lblNomeFornecedor3.setText("UF:");

        tfFornecedorUf.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        tfFornecedorUf.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblNomeFornecedor4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNomeFornecedor4.setForeground(new java.awt.Color(0, 69, 139));
        lblNomeFornecedor4.setText("Telefone Fixo:");

        tfFornecedorTelFixo.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        tfFornecedorTelFixo.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        tfFornecedorTelCelular.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        tfFornecedorTelCelular.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblNomeFornecedor6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNomeFornecedor6.setForeground(new java.awt.Color(0, 69, 139));
        lblNomeFornecedor6.setText("Celular:");

        lblNomeFornecedor7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNomeFornecedor7.setForeground(new java.awt.Color(0, 69, 139));
        lblNomeFornecedor7.setText("E-mail:");

        tfFornecedorEmail.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        tfFornecedorEmail.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblNomeFornecedor8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNomeFornecedor8.setForeground(new java.awt.Color(0, 69, 139));
        lblNomeFornecedor8.setText("Site:");

        tfFornecedorSite.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        tfFornecedorSite.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblNomeFornecedor9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNomeFornecedor9.setForeground(new java.awt.Color(0, 69, 139));
        lblNomeFornecedor9.setText("Vendedor:");

        tfFornecedorVendedor.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        tfFornecedorVendedor.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        btnCadastrarFornecedor.setBackground(new java.awt.Color(102, 0, 102));
        btnCadastrarFornecedor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCadastrarFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cadastroPqn.png"))); // NOI18N
        btnCadastrarFornecedor.setToolTipText("Cadastrar");
        btnCadastrarFornecedor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCadastrarFornecedor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCadastrarFornecedor.setPreferredSize(new java.awt.Dimension(0, 0));
        btnCadastrarFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarFornecedorActionPerformed(evt);
            }
        });

        btnAlterarFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/AlterarPq.png"))); // NOI18N
        btnAlterarFornecedor.setToolTipText("Alterar");
        btnAlterarFornecedor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnAlterarFornecedor.setEnabled(false);

        lblNomeFornecedor10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNomeFornecedor10.setForeground(new java.awt.Color(0, 69, 139));
        lblNomeFornecedor10.setText("Ramal:");

        tfFornecedorRamalVendedor.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        tfFornecedorRamalVendedor.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblNomeFornecedor11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNomeFornecedor11.setForeground(new java.awt.Color(0, 69, 139));
        lblNomeFornecedor11.setText("Cidade:");

        tfFornecedorEndereco1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        tfFornecedorEndereco1.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblNomeFornecedor12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNomeFornecedor12.setForeground(new java.awt.Color(0, 69, 139));
        lblNomeFornecedor12.setText("Complemento:");

        lblNomeFornecedor13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNomeFornecedor13.setForeground(new java.awt.Color(0, 69, 139));
        lblNomeFornecedor13.setText("Nº:");

        tfFornecedorUf1.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        tfFornecedorUf1.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        tfFornecedorEndereco2.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        tfFornecedorEndereco2.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblNomeFornecedor14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNomeFornecedor14.setForeground(new java.awt.Color(0, 69, 139));
        lblNomeFornecedor14.setText("CEP:");

        tfFornecedorEndereco3.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        tfFornecedorEndereco3.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel57.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel57.setForeground(new java.awt.Color(0, 69, 139));
        jLabel57.setText("Status:");

        javax.swing.GroupLayout pnlDadosFornecedorLayout = new javax.swing.GroupLayout(pnlDadosFornecedor);
        pnlDadosFornecedor.setLayout(pnlDadosFornecedorLayout);
        pnlDadosFornecedorLayout.setHorizontalGroup(
            pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosFornecedorLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel57)
                    .addComponent(lblNomeFornecedor9)
                    .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(pnlDadosFornecedorLayout.createSequentialGroup()
                            .addComponent(jLabel50)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfFornecedorCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDadosFornecedorLayout.createSequentialGroup()
                            .addComponent(jLabel49)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tfFornecedorCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlDadosFornecedorLayout.createSequentialGroup()
                        .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNomeFornecedor)
                            .addComponent(lblNomeFornecedor1)
                            .addComponent(lblNomeFornecedor4)
                            .addComponent(lblNomeFornecedor7)
                            .addComponent(lblNomeFornecedor12)
                            .addComponent(lblNomeFornecedor14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDadosFornecedorLayout.createSequentialGroup()
                                .addComponent(tfFornecedorEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNomeFornecedor13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfFornecedorUf1, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                            .addGroup(pnlDadosFornecedorLayout.createSequentialGroup()
                                .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tfFornecedorEndereco1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfFornecedorEmail)
                                    .addComponent(tfFornecedorVendedor)
                                    .addComponent(tfFornecedorEndereco3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                                    .addComponent(tfFornecedorTelFixo, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(pnlDadosFornecedorLayout.createSequentialGroup()
                                        .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblNomeFornecedor2)
                                            .addComponent(lblNomeFornecedor11))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(tfFornecedorBairro)
                                            .addGroup(pnlDadosFornecedorLayout.createSequentialGroup()
                                                .addComponent(tfFornecedorEndereco2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblNomeFornecedor3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tfFornecedorUf, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(pnlDadosFornecedorLayout.createSequentialGroup()
                                        .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(pnlDadosFornecedorLayout.createSequentialGroup()
                                                .addComponent(lblNomeFornecedor10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(tfFornecedorRamalVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(pnlDadosFornecedorLayout.createSequentialGroup()
                                                .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lblNomeFornecedor6)
                                                    .addComponent(lblNomeFornecedor8))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(tfFornecedorTelCelular, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(tfFornecedorSite, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnAlterarFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnCadastrarFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(8, 8, 8))))
                            .addComponent(tfFornecedorNome))))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        pnlDadosFornecedorLayout.setVerticalGroup(
            pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosFornecedorLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel49)
                    .addComponent(tfFornecedorCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel50)
                    .addComponent(tfFornecedorCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfFornecedorNome, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomeFornecedor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeFornecedor1)
                    .addComponent(tfFornecedorEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomeFornecedor13)
                    .addComponent(tfFornecedorUf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfFornecedorEndereco1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomeFornecedor12)
                    .addComponent(lblNomeFornecedor2)
                    .addComponent(tfFornecedorBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeFornecedor14)
                    .addComponent(tfFornecedorEndereco3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomeFornecedor11)
                    .addComponent(tfFornecedorEndereco2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomeFornecedor3)
                    .addComponent(tfFornecedorUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeFornecedor4)
                    .addComponent(tfFornecedorTelFixo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfFornecedorTelCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomeFornecedor6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfFornecedorSite, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfFornecedorEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNomeFornecedor7)
                        .addComponent(lblNomeFornecedor8)))
                .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDadosFornecedorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNomeFornecedor9)
                            .addComponent(tfFornecedorVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNomeFornecedor10)
                            .addComponent(tfFornecedorRamalVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel57)
                        .addContainerGap(58, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDadosFornecedorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCadastrarFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAlterarFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17))))
        );

        pnlFornecedorOpBusca.setBackground(new java.awt.Color(204, 204, 255));

        tfFornecedorOpBuscaCod.setBackground(new java.awt.Color(204, 255, 204));
        tfFornecedorOpBuscaCod.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        tfFornecedorOpBuscaCod.setForeground(java.awt.Color.lightGray);
        tfFornecedorOpBuscaCod.setText("Codigo");
        tfFornecedorOpBuscaCod.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfFornecedorOpBuscaCodFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfFornecedorOpBuscaCodFocusLost(evt);
            }
        });

        tfFornecedorOpBuscaCnpj.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        tfFornecedorOpBuscaCnpj.setForeground(java.awt.Color.lightGray);
        tfFornecedorOpBuscaCnpj.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfFornecedorOpBuscaCnpj.setText("CNPJ");
        tfFornecedorOpBuscaCnpj.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfFornecedorOpBuscaCnpjFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfFornecedorOpBuscaCnpjFocusLost(evt);
            }
        });

        tfFornecedorOpBuscaNome.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        tfFornecedorOpBuscaNome.setForeground(java.awt.Color.lightGray);
        tfFornecedorOpBuscaNome.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfFornecedorOpBuscaNome.setText("Nome / R .S.");
        tfFornecedorOpBuscaNome.setToolTipText("");
        tfFornecedorOpBuscaNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfFornecedorOpBuscaNomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfFornecedorOpBuscaNomeFocusLost(evt);
            }
        });

        jlFornecedorResultBusca.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jlFornecedorResultBusca.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jlFornecedorResultBusca);

        javax.swing.GroupLayout pnlFornecedorOpBuscaLayout = new javax.swing.GroupLayout(pnlFornecedorOpBusca);
        pnlFornecedorOpBusca.setLayout(pnlFornecedorOpBuscaLayout);
        pnlFornecedorOpBuscaLayout.setHorizontalGroup(
            pnlFornecedorOpBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFornecedorOpBuscaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlFornecedorOpBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfFornecedorOpBuscaNome)
                    .addGroup(pnlFornecedorOpBuscaLayout.createSequentialGroup()
                        .addGroup(pnlFornecedorOpBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfFornecedorOpBuscaCod, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfFornecedorOpBuscaCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 80, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        pnlFornecedorOpBuscaLayout.setVerticalGroup(
            pnlFornecedorOpBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFornecedorOpBuscaLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(tfFornecedorOpBuscaCod, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfFornecedorOpBuscaCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfFornecedorOpBuscaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlFornecedorTituloOpBusca.setBackground(new java.awt.Color(153, 153, 255));

        jLabel52.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel52.setForeground(new java.awt.Color(255, 255, 255));
        jLabel52.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel52.setText("Opções");

        javax.swing.GroupLayout pnlFornecedorTituloOpBuscaLayout = new javax.swing.GroupLayout(pnlFornecedorTituloOpBusca);
        pnlFornecedorTituloOpBusca.setLayout(pnlFornecedorTituloOpBuscaLayout);
        pnlFornecedorTituloOpBuscaLayout.setHorizontalGroup(
            pnlFornecedorTituloOpBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFornecedorTituloOpBuscaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel52, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnlFornecedorTituloOpBuscaLayout.setVerticalGroup(
            pnlFornecedorTituloOpBuscaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFornecedorTituloOpBuscaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel52)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlFornecedorOpBusca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlFornecedorTituloOpBusca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnlDadosFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlFornecedorTituloOpBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlFornecedorOpBusca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlDadosFornecedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        setBounds(0, 0, 1018, 581);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarFornecedorActionPerformed
       Fornecedor fornecedor = new Fornecedor();
       FornecedorController fornecedorController = new FornecedorController();
       
       // recebe os dados do fornecedor
       fornecedor.setCodFornecedor(Integer.valueOf(tfFornecedorCodigo.getText()));
       fornecedor.setCnpjFornecedor(tfFornecedorCnpj.getText());
       fornecedor.setNomeFornecedor(tfFornecedorNome.getText());
       fornecedor.setEndereco(tfFornecedorEndereco.getText());
       fornecedor.setBairro(tfFornecedorBairro.getText());
       fornecedor.setUf(tfFornecedorUf.getText());
       fornecedor.setTelFixo(tfFornecedorTelFixo.getText());
       fornecedor.setTelCel(tfFornecedorTelCelular.getText());
       fornecedor.setEmail(tfFornecedorEmail.getText());
       fornecedor.setSite(tfFornecedorSite.getText());
       fornecedor.setVendedor(tfFornecedorVendedor.getText());
       fornecedor.setRamal(tfFornecedorRamalVendedor.getText());
       
       // testa se os dados do fornecedor s�o v�lidos
       if(fornecedorController.validarFornecedor(fornecedor)) {
           FornecedorCRUD fornecedorCRUD = new FornecedorCRUD();
           
           // cadastra o fornecedor no banco de dados
           fornecedorCRUD.inserirFornecedor(fornecedor);
           
           // limpa os campos do formulario
           FrmPrincipal.limparCampos(tfFornecedorCodigo, tfFornecedorCnpj, tfFornecedorNome,
                   tfFornecedorEndereco, tfFornecedorBairro, tfFornecedorUf, tfFornecedorTelFixo,
                   tfFornecedorTelCelular, tfFornecedorEmail, tfFornecedorSite, 
                   tfFornecedorVendedor, tfFornecedorRamalVendedor);
       }
    }//GEN-LAST:event_btnCadastrarFornecedorActionPerformed

    private void tfFornecedorOpBuscaCodFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfFornecedorOpBuscaCodFocusGained
        tfFornecedorOpBuscaCod.setForeground(Color.red);
        tfFornecedorOpBuscaCod.setText("");
        
    }//GEN-LAST:event_tfFornecedorOpBuscaCodFocusGained

    private void tfFornecedorOpBuscaCodFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfFornecedorOpBuscaCodFocusLost
       if(tfFornecedorOpBuscaCod.getText().isEmpty()){
        tfFornecedorOpBuscaCod.setForeground(Color.LIGHT_GRAY);
        tfFornecedorOpBuscaCod.setText("Código");
       }
    }//GEN-LAST:event_tfFornecedorOpBuscaCodFocusLost

    private void tfFornecedorOpBuscaCnpjFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfFornecedorOpBuscaCnpjFocusGained
         tfFornecedorOpBuscaCnpj.setForeground(Color.black);
        tfFornecedorOpBuscaCnpj.setText("");
    }//GEN-LAST:event_tfFornecedorOpBuscaCnpjFocusGained

    private void tfFornecedorOpBuscaCnpjFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfFornecedorOpBuscaCnpjFocusLost
         if(tfFornecedorOpBuscaCnpj.getText().isEmpty()){
        tfFornecedorOpBuscaCnpj.setForeground(Color.LIGHT_GRAY);
        tfFornecedorOpBuscaCnpj.setText("CNPJ");
       }
    }//GEN-LAST:event_tfFornecedorOpBuscaCnpjFocusLost

    private void tfFornecedorOpBuscaNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfFornecedorOpBuscaNomeFocusGained
         tfFornecedorOpBuscaNome.setForeground(Color.black);
        tfFornecedorOpBuscaNome.setText("");
    }//GEN-LAST:event_tfFornecedorOpBuscaNomeFocusGained

    private void tfFornecedorOpBuscaNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfFornecedorOpBuscaNomeFocusLost
        if(tfFornecedorOpBuscaNome.getText().isEmpty()){
        tfFornecedorOpBuscaNome.setForeground(Color.LIGHT_GRAY);
        tfFornecedorOpBuscaNome.setText("Nome / R.S.");
       }
    }//GEN-LAST:event_tfFornecedorOpBuscaNomeFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarFornecedor;
    private javax.swing.JButton btnCadastrarFornecedor;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList jlFornecedorResultBusca;
    private javax.swing.JLabel lblNomeFornecedor;
    private javax.swing.JLabel lblNomeFornecedor1;
    private javax.swing.JLabel lblNomeFornecedor10;
    private javax.swing.JLabel lblNomeFornecedor11;
    private javax.swing.JLabel lblNomeFornecedor12;
    private javax.swing.JLabel lblNomeFornecedor13;
    private javax.swing.JLabel lblNomeFornecedor14;
    private javax.swing.JLabel lblNomeFornecedor2;
    private javax.swing.JLabel lblNomeFornecedor3;
    private javax.swing.JLabel lblNomeFornecedor4;
    private javax.swing.JLabel lblNomeFornecedor6;
    private javax.swing.JLabel lblNomeFornecedor7;
    private javax.swing.JLabel lblNomeFornecedor8;
    private javax.swing.JLabel lblNomeFornecedor9;
    private javax.swing.JPanel pnlDadosFornecedor;
    private javax.swing.JPanel pnlFornecedorOpBusca;
    private javax.swing.JPanel pnlFornecedorTituloOpBusca;
    private javax.swing.JTextField tfFornecedorBairro;
    private javax.swing.JTextField tfFornecedorCnpj;
    private javax.swing.JTextField tfFornecedorCodigo;
    private javax.swing.JTextField tfFornecedorEmail;
    private javax.swing.JTextField tfFornecedorEndereco;
    private javax.swing.JTextField tfFornecedorEndereco1;
    private javax.swing.JTextField tfFornecedorEndereco2;
    private javax.swing.JTextField tfFornecedorEndereco3;
    private javax.swing.JTextField tfFornecedorNome;
    private javax.swing.JTextField tfFornecedorOpBuscaCnpj;
    private javax.swing.JTextField tfFornecedorOpBuscaCod;
    private javax.swing.JTextField tfFornecedorOpBuscaNome;
    private javax.swing.JTextField tfFornecedorRamalVendedor;
    private javax.swing.JTextField tfFornecedorSite;
    private javax.swing.JTextField tfFornecedorTelCelular;
    private javax.swing.JTextField tfFornecedorTelFixo;
    private javax.swing.JTextField tfFornecedorUf;
    private javax.swing.JTextField tfFornecedorUf1;
    private javax.swing.JTextField tfFornecedorVendedor;
    // End of variables declaration//GEN-END:variables
}
