package view;

import controller.FornecedorController;
import crud.CidadeCRUD;
import crud.EstadoCRUD;
import crud.FornecedorCRUD;
import domain.Cidade;
import domain.Estado;
import domain.Fornecedor;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Adriano
 */
public class FrmCadastrarFornecedor extends javax.swing.JDialog {

    Fornecedor fornecedor = new Fornecedor();

    /**
     * Creates new form FrmCadastrarFornecedor
     *
     * @param parent
     * @param modal
     */
    public FrmCadastrarFornecedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(this);
        this.carregarCbUf();

        FrmPrincipal.habilitarDesabilitarComponente(false, tfFornecedorBairro, tfFornecedorCep, tfFornecedorComplemento, tfFornecedorEmail, tfFornecedorLogradouro,
                tfFornecedorNumero, tfFornecedorRamalVendedor, tfFornecedorSite, tfFornecedorTelCel, tfFornecedorTelFixo, tfFornecedorVendedor);
        FrmPrincipal.habilitarDesabilitarComponente(false, cbFornecedorCidade, cbFornecedorUf);
        FrmPrincipal.habilitarDesabilitarComponente(false, rbFornecedorStatusInat, rbFornecedortatusAtiv);
        FrmPrincipal.habilitarDesabilitarComponente(false, btnFornecedorAlterar,btnFornecedorCadastrar,btnFornecedorAdicionar);
    }

    // Carrega lista de Ufs
    public void carregarCbUf() {
        EstadoCRUD estadoCRUD = new EstadoCRUD();

        cbFornecedorUf.removeAllItems();

        for (Estado estado : estadoCRUD.consultarEstado()) {
            cbFornecedorUf.addItem(estado.getUf());
        }
    }

    // Carrega lista de Cidades
    public void carregarCbCidades(JComboBox cb, String uf) {
        CidadeCRUD cidadeCRUD = new CidadeCRUD();

        cb.removeAllItems();

        for (Cidade cidade : cidadeCRUD.consultarCidade(uf)) {
            cb.addItem(cidade.getNome());
        }
    }

    private ArrayList<Fornecedor> pesquisarFornecedorCaretUpdate() {
        FornecedorCRUD fornecedorCrud = new FornecedorCRUD();
        ArrayList<Fornecedor> listaFornecedor = new ArrayList<>();

        listaFornecedor = fornecedorCrud.consultarFornecedores(tfFornecedorCodigo, tfFornecedorNome, tfFornecedorCnpj);

        if (listaFornecedor.size() > 0) {
            DefaultTableModel modelo = (DefaultTableModel) tbAdicionarFornecedorResultBusca.getModel();
            modelo.setRowCount(0);
            for (Fornecedor fornecedo : listaFornecedor) {
                modelo.addRow(new Object[]{fornecedo.getNome()});
            }

        }

        return listaFornecedor;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rgFornecedorStatus = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        pnlDadosFornecedor = new javax.swing.JPanel();
        lblNomeFornecedor1 = new javax.swing.JLabel();
        tfFornecedorLogradouro = new javax.swing.JTextField();
        lblNomeFornecedor2 = new javax.swing.JLabel();
        tfFornecedorBairro = new javax.swing.JTextField();
        lblNomeFornecedor3 = new javax.swing.JLabel();
        lblNomeFornecedor4 = new javax.swing.JLabel();
        lblNomeFornecedor6 = new javax.swing.JLabel();
        lblNomeFornecedor7 = new javax.swing.JLabel();
        tfFornecedorEmail = new javax.swing.JTextField();
        lblNomeFornecedor8 = new javax.swing.JLabel();
        tfFornecedorSite = new javax.swing.JTextField();
        lblNomeFornecedor9 = new javax.swing.JLabel();
        tfFornecedorVendedor = new javax.swing.JTextField();
        btnFornecedorCadastrar = new javax.swing.JButton();
        btnFornecedorAlterar = new javax.swing.JButton();
        lblNomeFornecedor10 = new javax.swing.JLabel();
        tfFornecedorRamalVendedor = new javax.swing.JTextField();
        lblNomeFornecedor11 = new javax.swing.JLabel();
        tfFornecedorComplemento = new javax.swing.JTextField();
        lblNomeFornecedor12 = new javax.swing.JLabel();
        lblNomeFornecedor13 = new javax.swing.JLabel();
        tfFornecedorNumero = new javax.swing.JTextField();
        lblNomeFornecedor14 = new javax.swing.JLabel();
        cbFornecedorCidade = new javax.swing.JComboBox();
        cbFornecedorUf = new javax.swing.JComboBox();
        tfFornecedorCep = new javax.swing.JFormattedTextField(FrmPrincipal.MascararCampos("##.###-###"));
        tfFornecedorTelFixo = new javax.swing.JFormattedTextField(FrmPrincipal.MascararCampos("(##)####-####"));
        tfFornecedorTelCel = new javax.swing.JFormattedTextField(FrmPrincipal.MascararCampos("(##)#####-####"));
        jScrollPane2 = new javax.swing.JScrollPane();
        tbAdicionarFornecedorResultBusca = new javax.swing.JTable();
        btnFornecedorAdicionar = new javax.swing.JButton();
        bordaFornecedorPesquisa = new javax.swing.JPanel();
        tfFornecedorCodigo = new javax.swing.JTextField();
        tfFornecedorCnpj = new javax.swing.JFormattedTextField(FrmPrincipal.MascararCampos("##.###.###/####-##"));
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        lblNomeFornecedor = new javax.swing.JLabel();
        tfFornecedorNome = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        cb_novoFornecedor = new javax.swing.JCheckBox();
        rbFornecedortatusAtiv = new javax.swing.JRadioButton();
        rbFornecedorStatusInat = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel4.setBackground(new java.awt.Color(153, 153, 255));
        jPanel4.setBorder(null);

        jLabel51.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel51.setForeground(new java.awt.Color(255, 255, 255));
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel51.setText("Dados do Fornecedor");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel51, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel51)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlDadosFornecedor.setBackground(new java.awt.Color(204, 204, 255));
        pnlDadosFornecedor.setBorder(null);

        lblNomeFornecedor1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNomeFornecedor1.setForeground(new java.awt.Color(0, 69, 139));
        lblNomeFornecedor1.setText("Logradouro:");

        tfFornecedorLogradouro.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        tfFornecedorLogradouro.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblNomeFornecedor2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNomeFornecedor2.setForeground(new java.awt.Color(0, 69, 139));
        lblNomeFornecedor2.setText("Bairro:");

        tfFornecedorBairro.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        tfFornecedorBairro.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblNomeFornecedor3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNomeFornecedor3.setForeground(new java.awt.Color(0, 69, 139));
        lblNomeFornecedor3.setText("UF:");

        lblNomeFornecedor4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNomeFornecedor4.setForeground(new java.awt.Color(0, 69, 139));
        lblNomeFornecedor4.setText("Telefone Fixo:");

        lblNomeFornecedor6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNomeFornecedor6.setForeground(new java.awt.Color(0, 69, 139));
        lblNomeFornecedor6.setText("Celular:");

        lblNomeFornecedor7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNomeFornecedor7.setForeground(new java.awt.Color(0, 69, 139));
        lblNomeFornecedor7.setText("E-mail:");

        tfFornecedorEmail.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        tfFornecedorEmail.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblNomeFornecedor8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNomeFornecedor8.setForeground(new java.awt.Color(0, 69, 139));
        lblNomeFornecedor8.setText("Site:");

        tfFornecedorSite.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        tfFornecedorSite.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblNomeFornecedor9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNomeFornecedor9.setForeground(new java.awt.Color(0, 69, 139));
        lblNomeFornecedor9.setText("Vendedor:");

        tfFornecedorVendedor.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        tfFornecedorVendedor.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        btnFornecedorCadastrar.setBackground(new java.awt.Color(102, 0, 102));
        btnFornecedorCadastrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnFornecedorCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cadastroPqn.png"))); // NOI18N
        btnFornecedorCadastrar.setToolTipText("Cadastrar");
        btnFornecedorCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnFornecedorCadastrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFornecedorCadastrar.setPreferredSize(new java.awt.Dimension(0, 0));
        btnFornecedorCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFornecedorCadastrarActionPerformed(evt);
            }
        });

        btnFornecedorAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/AlterarPq.png"))); // NOI18N
        btnFornecedorAlterar.setToolTipText("Alterar");
        btnFornecedorAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnFornecedorAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFornecedorAlterarActionPerformed(evt);
            }
        });

        lblNomeFornecedor10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNomeFornecedor10.setForeground(new java.awt.Color(0, 69, 139));
        lblNomeFornecedor10.setText("Ramal:");

        tfFornecedorRamalVendedor.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        tfFornecedorRamalVendedor.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblNomeFornecedor11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNomeFornecedor11.setForeground(new java.awt.Color(0, 69, 139));
        lblNomeFornecedor11.setText("Cidade:");

        tfFornecedorComplemento.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        tfFornecedorComplemento.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblNomeFornecedor12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNomeFornecedor12.setForeground(new java.awt.Color(0, 69, 139));
        lblNomeFornecedor12.setText("Complemento:");

        lblNomeFornecedor13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNomeFornecedor13.setForeground(new java.awt.Color(0, 69, 139));
        lblNomeFornecedor13.setText("Nº:");

        tfFornecedorNumero.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        tfFornecedorNumero.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblNomeFornecedor14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNomeFornecedor14.setForeground(new java.awt.Color(0, 69, 139));
        lblNomeFornecedor14.setText("CEP:");

        cbFornecedorCidade.setBackground(new java.awt.Color(255, 255, 255));
        cbFornecedorCidade.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        cbFornecedorUf.setBackground(new java.awt.Color(255, 255, 255));
        cbFornecedorUf.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        cbFornecedorUf.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbFornecedorUfItemStateChanged(evt);
            }
        });

        tfFornecedorCep.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        tfFornecedorTelFixo.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        tfFornecedorTelCel.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N

        tbAdicionarFornecedorResultBusca.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fornecedores"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbAdicionarFornecedorResultBusca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbAdicionarFornecedorResultBuscaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbAdicionarFornecedorResultBusca);

        btnFornecedorAdicionar.setText("Adicionar");
        btnFornecedorAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFornecedorAdicionarActionPerformed(evt);
            }
        });

        bordaFornecedorPesquisa.setBackground(new java.awt.Color(204, 204, 255));
        bordaFornecedorPesquisa.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255), 2), "Pesquisar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        tfFornecedorCodigo.setBackground(new java.awt.Color(204, 255, 204));
        tfFornecedorCodigo.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        tfFornecedorCodigo.setForeground(new java.awt.Color(255, 0, 0));
        tfFornecedorCodigo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfFornecedorCodigo.setName(""); // NOI18N
        tfFornecedorCodigo.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tfFornecedorCodigoCaretUpdate(evt);
            }
        });

        tfFornecedorCnpj.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        tfFornecedorCnpj.setName(""); // NOI18N
        tfFornecedorCnpj.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tfFornecedorCnpjCaretUpdate(evt);
            }
        });

        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(0, 69, 139));
        jLabel49.setText("Código:");

        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(0, 69, 139));
        jLabel50.setText("CNPJ:");

        lblNomeFornecedor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNomeFornecedor.setForeground(new java.awt.Color(0, 69, 139));
        lblNomeFornecedor.setText("Nome / Razão Social:");

        tfFornecedorNome.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        tfFornecedorNome.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        tfFornecedorNome.setName(""); // NOI18N
        tfFornecedorNome.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                tfFornecedorNomeCaretUpdate(evt);
            }
        });

        javax.swing.GroupLayout bordaFornecedorPesquisaLayout = new javax.swing.GroupLayout(bordaFornecedorPesquisa);
        bordaFornecedorPesquisa.setLayout(bordaFornecedorPesquisaLayout);
        bordaFornecedorPesquisaLayout.setHorizontalGroup(
            bordaFornecedorPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bordaFornecedorPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bordaFornecedorPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bordaFornecedorPesquisaLayout.createSequentialGroup()
                        .addGroup(bordaFornecedorPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel49)
                            .addComponent(jLabel50))
                        .addGap(105, 105, 105)
                        .addGroup(bordaFornecedorPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfFornecedorCnpj, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addComponent(tfFornecedorCodigo))
                        .addGap(0, 356, Short.MAX_VALUE))
                    .addGroup(bordaFornecedorPesquisaLayout.createSequentialGroup()
                        .addComponent(lblNomeFornecedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfFornecedorNome)))
                .addContainerGap())
        );
        bordaFornecedorPesquisaLayout.setVerticalGroup(
            bordaFornecedorPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bordaFornecedorPesquisaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bordaFornecedorPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfFornecedorCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel49))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bordaFornecedorPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfFornecedorCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel50))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(bordaFornecedorPesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeFornecedor)
                    .addComponent(tfFornecedorNome, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 255), 2), "Opções", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        cb_novoFornecedor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cb_novoFornecedor.setForeground(new java.awt.Color(0, 69, 139));
        cb_novoFornecedor.setText("Novo Fornecedor");
        cb_novoFornecedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cb_novoFornecedorMouseClicked(evt);
            }
        });

        rgFornecedorStatus.add(rbFornecedortatusAtiv);
        rbFornecedortatusAtiv.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbFornecedortatusAtiv.setForeground(new java.awt.Color(0, 69, 139));
        rbFornecedortatusAtiv.setText("Ativo");
        rbFornecedortatusAtiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFornecedortatusAtivActionPerformed(evt);
            }
        });

        rgFornecedorStatus.add(rbFornecedorStatusInat);
        rbFornecedorStatusInat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbFornecedorStatusInat.setForeground(new java.awt.Color(0, 69, 139));
        rbFornecedorStatusInat.setText("Inativo");
        rbFornecedorStatusInat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFornecedorStatusInatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cb_novoFornecedor)
                    .addComponent(rbFornecedortatusAtiv)
                    .addComponent(rbFornecedorStatusInat))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(cb_novoFornecedor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(rbFornecedortatusAtiv)
                .addGap(26, 26, 26)
                .addComponent(rbFornecedorStatusInat)
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout pnlDadosFornecedorLayout = new javax.swing.GroupLayout(pnlDadosFornecedor);
        pnlDadosFornecedor.setLayout(pnlDadosFornecedorLayout);
        pnlDadosFornecedorLayout.setHorizontalGroup(
            pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDadosFornecedorLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNomeFornecedor1)
                    .addComponent(lblNomeFornecedor14)
                    .addGroup(pnlDadosFornecedorLayout.createSequentialGroup()
                        .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNomeFornecedor12)
                            .addComponent(lblNomeFornecedor4)
                            .addComponent(lblNomeFornecedor7)
                            .addComponent(lblNomeFornecedor9))
                        .addGap(57, 57, 57)
                        .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDadosFornecedorLayout.createSequentialGroup()
                                .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfFornecedorComplemento, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                                    .addComponent(tfFornecedorCep, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfFornecedorEmail)
                                    .addComponent(tfFornecedorVendedor))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlDadosFornecedorLayout.createSequentialGroup()
                                        .addComponent(lblNomeFornecedor10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tfFornecedorRamalVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlDadosFornecedorLayout.createSequentialGroup()
                                            .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addGroup(pnlDadosFornecedorLayout.createSequentialGroup()
                                                    .addComponent(lblNomeFornecedor8)
                                                    .addGap(28, 28, 28)
                                                    .addComponent(tfFornecedorSite))
                                                .addGroup(pnlDadosFornecedorLayout.createSequentialGroup()
                                                    .addComponent(lblNomeFornecedor11)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(cbFornecedorCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(lblNomeFornecedor3)
                                            .addGap(6, 6, 6)
                                            .addComponent(cbFornecedorUf, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(pnlDadosFornecedorLayout.createSequentialGroup()
                                            .addComponent(lblNomeFornecedor2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(tfFornecedorBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addComponent(tfFornecedorTelFixo, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlDadosFornecedorLayout.createSequentialGroup()
                                .addComponent(tfFornecedorLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblNomeFornecedor13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfFornecedorNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(pnlDadosFornecedorLayout.createSequentialGroup()
                        .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlDadosFornecedorLayout.createSequentialGroup()
                                .addComponent(lblNomeFornecedor6)
                                .addGap(18, 18, 18)
                                .addComponent(tfFornecedorTelCel, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(bordaFornecedorPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlDadosFornecedorLayout.createSequentialGroup()
                        .addComponent(btnFornecedorCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(97, 97, 97)
                        .addComponent(btnFornecedorAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFornecedorAdicionar))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
        );
        pnlDadosFornecedorLayout.setVerticalGroup(
            pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosFornecedorLayout.createSequentialGroup()
                .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDadosFornecedorLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bordaFornecedorPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNomeFornecedor4)
                            .addComponent(tfFornecedorTelFixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNomeFornecedor6)
                            .addComponent(tfFornecedorTelCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNomeFornecedor1)
                            .addComponent(tfFornecedorLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNomeFornecedor13)
                            .addComponent(tfFornecedorNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfFornecedorComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNomeFornecedor12)
                            .addComponent(lblNomeFornecedor2)
                            .addComponent(tfFornecedorBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfFornecedorCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNomeFornecedor14)
                            .addComponent(lblNomeFornecedor11)
                            .addComponent(lblNomeFornecedor3)
                            .addComponent(cbFornecedorUf, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbFornecedorCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfFornecedorEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNomeFornecedor7)
                            .addComponent(lblNomeFornecedor8)
                            .addComponent(tfFornecedorSite, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfFornecedorVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNomeFornecedor10)
                            .addComponent(tfFornecedorRamalVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNomeFornecedor9)))
                    .addGroup(pnlDadosFornecedorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlDadosFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnFornecedorCadastrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnFornecedorAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnFornecedorAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlDadosFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 1219, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDadosFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBounds(0, 0, 1249, 579);
    }// </editor-fold>//GEN-END:initComponents


    private void btnFornecedorCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFornecedorCadastrarActionPerformed
        Fornecedor fornecedor = new Fornecedor();

        FornecedorController fornecedorController = new FornecedorController();

        // recebe os dados do fornecedor
        fornecedor.setCodFornecedor(Integer.valueOf(tfFornecedorCodigo.getText()));
        fornecedor.setCnpj(tfFornecedorCnpj.getText());
        fornecedor.setNome(tfFornecedorNome.getText());
        fornecedor.setTelFixo(tfFornecedorTelFixo.getText());
        fornecedor.setTelCel(tfFornecedorTelCel.getText());
        fornecedor.setEmail(tfFornecedorEmail.getText());
        fornecedor.setSite(tfFornecedorSite.getText());
        fornecedor.setVendedor(tfFornecedorVendedor.getText());
        fornecedor.setRamal(tfFornecedorRamalVendedor.getText());

        // define o status do fornecedor
        if (rbFornecedortatusAtiv.isSelected()) {
            // ativo
            fornecedor.setStatus(true);
        } else if (rbFornecedorStatusInat.isSelected()) {
            // inativo
            fornecedor.setStatus(false);
        }

        fornecedor.setCod(Integer.valueOf(tfFornecedorCodigo.getText()));
        fornecedor.setLogradouro(tfFornecedorLogradouro.getText());
        fornecedor.setNumero(Integer.parseInt(tfFornecedorNumero.getText()));
        fornecedor.setComplemento(tfFornecedorComplemento.getText());
        fornecedor.setBairro(tfFornecedorBairro.getText());
        fornecedor.setCep(tfFornecedorCep.getText());
        fornecedor.setCidade(cbFornecedorCidade.getSelectedItem().toString());
        fornecedor.setUf(cbFornecedorUf.getSelectedItem().toString());

        // testa se os dados do fornecedor são válidos
        if (fornecedorController.validarFornecedor(fornecedor)) {
            FornecedorCRUD fornecedorCRUD = new FornecedorCRUD();

            // cadastra o fornecedor no banco de dados
            fornecedorCRUD.inserirFornecedor(fornecedor);

            // limpa os campos do formulario
            FrmPrincipal.limparCampos(tfFornecedorCodigo, tfFornecedorCnpj, tfFornecedorNome,
                    tfFornecedorLogradouro, tfFornecedorBairro, tfFornecedorTelFixo,
                    tfFornecedorTelCel, tfFornecedorEmail, tfFornecedorSite,
                    tfFornecedorVendedor, tfFornecedorRamalVendedor, tfFornecedorCep,
                    tfFornecedorNumero, tfFornecedorComplemento);
        }
    }//GEN-LAST:event_btnFornecedorCadastrarActionPerformed


    private void rbFornecedortatusAtivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFornecedortatusAtivActionPerformed
        int op = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja ativar o fornecedor?");
        if (op == 0) {
            // opção "sim"
        } else {
            rbFornecedorStatusInat.setSelected(true);
        }
    }//GEN-LAST:event_rbFornecedortatusAtivActionPerformed

    private void rbFornecedorStatusInatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFornecedorStatusInatActionPerformed
        int op = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja desativar o fornecedor?");
        if (op == 0) {
            // opção "sim"
        } else {
            rbFornecedortatusAtiv.setSelected(true);
        }
    }//GEN-LAST:event_rbFornecedorStatusInatActionPerformed

    private void btnFornecedorAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFornecedorAlterarActionPerformed
        Fornecedor fornecedor = new Fornecedor();

        fornecedor.setCodFornecedor(Integer.parseInt(tfFornecedorCodigo.getText()));
        fornecedor.setCnpj(tfFornecedorCnpj.getText());
        fornecedor.setNome(tfFornecedorNome.getText());
        fornecedor.setTelFixo(tfFornecedorTelFixo.getText());
        fornecedor.setTelCel(tfFornecedorTelCel.getText());
        fornecedor.setEmail(tfFornecedorEmail.getText());
        fornecedor.setSite(tfFornecedorSite.getText());
        fornecedor.setVendedor(tfFornecedorVendedor.getText());
        fornecedor.setRamal(tfFornecedorRamalVendedor.getText());

        // define o status do fornecedor
        if (rbFornecedortatusAtiv.isSelected()) {
            // ativo
            fornecedor.setStatus(true);
        } else if (rbFornecedorStatusInat.isSelected()) {
            // inativo
            fornecedor.setStatus(false
            );
        }

        fornecedor.setLogradouro(tfFornecedorLogradouro.getText());
        fornecedor.setNumero(Integer.parseInt(tfFornecedorNumero.getText()));
        fornecedor.setComplemento(tfFornecedorComplemento.getText());
        fornecedor.setBairro(tfFornecedorBairro.getText());
        fornecedor.setCep(tfFornecedorCep.getText());
        fornecedor.setCidade(cbFornecedorCidade.getSelectedItem().toString());
        fornecedor.setUf(cbFornecedorUf.getSelectedItem().toString());

        FornecedorController fornecedorController = new FornecedorController();
        if (fornecedorController.validarFornecedor(fornecedor)) {
            FornecedorCRUD fornecedorCRUD = new FornecedorCRUD();

            fornecedorCRUD.atualizarFornecedor(fornecedor);

            FrmPrincipal.limparCampos(tfFornecedorCodigo, tfFornecedorCnpj, tfFornecedorNome,
                    tfFornecedorTelFixo, tfFornecedorTelCel, tfFornecedorEmail, tfFornecedorSite,
                    tfFornecedorVendedor, tfFornecedorRamalVendedor, tfFornecedorLogradouro,
                    tfFornecedorNumero, tfFornecedorComplemento, tfFornecedorBairro, tfFornecedorCep);
        }
    }//GEN-LAST:event_btnFornecedorAlterarActionPerformed

    private void cbFornecedorUfItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbFornecedorUfItemStateChanged
        if (evt.getStateChange() == 1) {
            carregarCbCidades(cbFornecedorCidade, cbFornecedorUf.getSelectedItem().toString());
        }
    }//GEN-LAST:event_cbFornecedorUfItemStateChanged

    private void tfFornecedorCodigoCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tfFornecedorCodigoCaretUpdate
        DefaultTableModel modelo = (DefaultTableModel) tbAdicionarFornecedorResultBusca.getModel();
        //se  o campo nao estiver vazio e nao estiver marcado para criar Novo Fornecedor  realiza a pesquisa
        if (!tfFornecedorCodigo.getText().isEmpty() && !cb_novoFornecedor.isSelected() && !btnFornecedorAlterar.isEnabled()) {
            this.pesquisarFornecedorCaretUpdate();
            //senao limpa a tabela de resultados
        } else {
            modelo.setRowCount(0);
        }
    }//GEN-LAST:event_tfFornecedorCodigoCaretUpdate

    private void tfFornecedorCnpjCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tfFornecedorCnpjCaretUpdate
        DefaultTableModel modelo = (DefaultTableModel) tbAdicionarFornecedorResultBusca.getModel();
        //se  o campo nao estiver vazio e nao estiver marcado para criar Novo Fornecedor  realiza a pesquisa
        String campo = FrmPrincipal.desmascarar(tfFornecedorCnpj.getText()).trim();
        System.out.println(campo);
        if (!campo.isEmpty() && !cb_novoFornecedor.isSelected() && !btnFornecedorAlterar.isEnabled()) {
            this.pesquisarFornecedorCaretUpdate();
            //senao limpa a tabela de resultados
        } else {
            modelo.setRowCount(0);
        }
    }//GEN-LAST:event_tfFornecedorCnpjCaretUpdate

    private void tfFornecedorNomeCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_tfFornecedorNomeCaretUpdate
        DefaultTableModel modelo = (DefaultTableModel) tbAdicionarFornecedorResultBusca.getModel();
        //se  o campo nao estiver vazio e nao estiver marcado para criar Novo Fornecedor e desativado btn de Alterar, realiza a pesquisa
        if (!tfFornecedorNome.getText().isEmpty() && !cb_novoFornecedor.isSelected() && !btnFornecedorAlterar.isEnabled()) {
            this.pesquisarFornecedorCaretUpdate();
            //senao limpa a tabela de resultados
        } else {
            modelo.setRowCount(0);
        }
    }//GEN-LAST:event_tfFornecedorNomeCaretUpdate

    private void tbAdicionarFornecedorResultBuscaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbAdicionarFornecedorResultBuscaMouseClicked
        FrmPrincipal.habilitarDesabilitarComponente(true, tfFornecedorBairro, tfFornecedorCep, tfFornecedorComplemento, tfFornecedorEmail, tfFornecedorLogradouro,
                tfFornecedorNumero, tfFornecedorRamalVendedor, tfFornecedorSite, tfFornecedorTelCel, tfFornecedorTelFixo, tfFornecedorVendedor);
        FrmPrincipal.habilitarDesabilitarComponente(true, cbFornecedorCidade, cbFornecedorUf);
        FrmPrincipal.habilitarDesabilitarComponente(true, rbFornecedorStatusInat, rbFornecedortatusAtiv);
        FrmPrincipal.habilitarDesabilitarComponente(true, btnFornecedorAlterar,btnFornecedorAdicionar);
        
        

    }//GEN-LAST:event_tbAdicionarFornecedorResultBuscaMouseClicked

    private void btnFornecedorAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFornecedorAdicionarActionPerformed
        DefaultTableModel modelo = (DefaultTableModel) tbAdicionarFornecedorResultBusca.getModel();
        FornecedorCRUD fornecedorCrud = new FornecedorCRUD();
        //pega o fornecedor escolhido na tabela e passa para variavel global
        this.fornecedor = fornecedorCrud.consultarFornecedorPorNome(modelo.getValueAt(tbAdicionarFornecedorResultBusca.getSelectedRow(), 0).toString());
        this.dispose();
    }//GEN-LAST:event_btnFornecedorAdicionarActionPerformed

    private void cb_novoFornecedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cb_novoFornecedorMouseClicked
        if (cb_novoFornecedor.isSelected()) {

            FornecedorCRUD fornecedorCRUD = new FornecedorCRUD();
            tfFornecedorCodigo.setText(String.valueOf(fornecedorCRUD.incrementCodFornecedor("inicializar")));
            tfFornecedorCodigo.setEditable(false);

            btnFornecedorAlterar.setEnabled(false);
            btnFornecedorCadastrar.setEnabled(true);

            // habilita os campos para cadastro
            FrmPrincipal.habilitarDesabilitarComponente(true, tfFornecedorBairro, tfFornecedorCep, tfFornecedorComplemento, tfFornecedorEmail, tfFornecedorLogradouro,
                    tfFornecedorNumero, tfFornecedorRamalVendedor, tfFornecedorSite, tfFornecedorTelCel, tfFornecedorTelFixo, tfFornecedorVendedor);
            FrmPrincipal.habilitarDesabilitarComponente(true, cbFornecedorCidade, cbFornecedorUf);
            FrmPrincipal.habilitarDesabilitarComponente(true, rbFornecedorStatusInat, rbFornecedortatusAtiv);

            tbAdicionarFornecedorResultBusca.removeAll();
            tbAdicionarFornecedorResultBusca.setEnabled(false);
        } else {

            tfFornecedorCodigo.setText("");
            tfFornecedorCodigo.setEditable(true);

            btnFornecedorAlterar.setEnabled(true);
            btnFornecedorCadastrar.setEnabled(false);

            // limpa os campos de cadastro
            FrmPrincipal.limparCampos(tfFornecedorTelFixo, tfFornecedorTelCel, tfFornecedorLogradouro,
                    tfFornecedorNumero, tfFornecedorComplemento, tfFornecedorBairro, tfFornecedorCep,
                    tfFornecedorEmail, tfFornecedorSite, tfFornecedorVendedor, tfFornecedorRamalVendedor);

            // resetar comboboxes
            cbFornecedorUf.removeAllItems();
            FrmPrincipal.carregarCbUf(cbFornecedorUf);
            cbFornecedorCidade.removeAllItems();
            FrmPrincipal.carregarCbCidades(cbFornecedorCidade, cbFornecedorUf.getSelectedItem().toString());

            // limpa e desbloqueia a tabela
            tbAdicionarFornecedorResultBusca.removeAll();
            tbAdicionarFornecedorResultBusca.setEnabled(true);

            // desabilita os campos para cadastro
            FrmPrincipal.habilitarDesabilitarComponente(false, tfFornecedorBairro, tfFornecedorCep, tfFornecedorComplemento, tfFornecedorEmail, tfFornecedorLogradouro,
                    tfFornecedorNumero, tfFornecedorRamalVendedor, tfFornecedorSite, tfFornecedorTelCel, tfFornecedorTelFixo, tfFornecedorVendedor);
            FrmPrincipal.habilitarDesabilitarComponente(false, cbFornecedorCidade, cbFornecedorUf);
            FrmPrincipal.habilitarDesabilitarComponente(false, rbFornecedorStatusInat, rbFornecedortatusAtiv);
        }
    }//GEN-LAST:event_cb_novoFornecedorMouseClicked

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bordaFornecedorPesquisa;
    private javax.swing.JButton btnFornecedorAdicionar;
    private javax.swing.JButton btnFornecedorAlterar;
    private javax.swing.JButton btnFornecedorCadastrar;
    private javax.swing.JComboBox cbFornecedorCidade;
    private javax.swing.JComboBox cbFornecedorUf;
    private javax.swing.JCheckBox cb_novoFornecedor;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblNomeFornecedor;
    private javax.swing.JLabel lblNomeFornecedor1;
    private javax.swing.JLabel lblNomeFornecedor10;
    private javax.swing.JLabel lblNomeFornecedor11;
    private javax.swing.JLabel lblNomeFornecedor12;
    private javax.swing.JLabel lblNomeFornecedor13;
    private javax.swing.JLabel lblNomeFornecedor14;
    private javax.swing.JLabel lblNomeFornecedor2;
    private javax.swing.JLabel lblNomeFornecedor3;
    private javax.swing.JLabel lblNomeFornecedor4;
    private javax.swing.JLabel lblNomeFornecedor6;
    private javax.swing.JLabel lblNomeFornecedor7;
    private javax.swing.JLabel lblNomeFornecedor8;
    private javax.swing.JLabel lblNomeFornecedor9;
    private javax.swing.JPanel pnlDadosFornecedor;
    private javax.swing.JRadioButton rbFornecedorStatusInat;
    private javax.swing.JRadioButton rbFornecedortatusAtiv;
    private javax.swing.ButtonGroup rgFornecedorStatus;
    private javax.swing.JTable tbAdicionarFornecedorResultBusca;
    private javax.swing.JTextField tfFornecedorBairro;
    private javax.swing.JFormattedTextField tfFornecedorCep;
    private javax.swing.JFormattedTextField tfFornecedorCnpj;
    private javax.swing.JTextField tfFornecedorCodigo;
    private javax.swing.JTextField tfFornecedorComplemento;
    private javax.swing.JTextField tfFornecedorEmail;
    private javax.swing.JTextField tfFornecedorLogradouro;
    private javax.swing.JTextField tfFornecedorNome;
    private javax.swing.JTextField tfFornecedorNumero;
    private javax.swing.JTextField tfFornecedorRamalVendedor;
    private javax.swing.JTextField tfFornecedorSite;
    private javax.swing.JFormattedTextField tfFornecedorTelCel;
    private javax.swing.JFormattedTextField tfFornecedorTelFixo;
    private javax.swing.JTextField tfFornecedorVendedor;
    // End of variables declaration//GEN-END:variables
}
